import { create } from 'zustand';
import { supabase } from '@/lib/supabase';

export interface ClockInRecord {
  id: string;
  userId: string;
  userName?: string; // Fetched via join
  /** FK to rooms.id. Null until an admin assigns the person a room. */
  roomId: string | null;
  /** Joined from `rooms` for display. Not a column on this table. */
  room: string;
  building: string | null;
  /** FK to purposes.id - why this person is here on this visit. */
  purposeId: string | null;
  purposeLabel: string | null;
  timeIn: Date;
  timeOut: Date | null;
  /** Generated by Postgres from time_out. Read-only. */
  status: 'active' | 'completed';
  /** Generated by Postgres. Null while the visit is still open. */
  durationMinutes: number | null;
}

interface RecordsState {
  records: ClockInRecord[];
  isLoading: boolean;
  
  // Actions
  addRecord: (record: {
    userId: string;
    roomId?: string | null;
    purposeId?: string | null;
    timeIn: Date;
  }) => Promise<{ success: boolean; error?: string; recordId?: string }>;
  clockOutRecord: (recordId: string) => Promise<{ success: boolean; error?: string }>;
  getActiveCount: () => number;
  getTodayCount: () => number;
  getCompletedTodayCount: () => number;
  /** Records still inside, i.e. clocked in with no time_out yet. */
  getActiveRecords: () => ClockInRecord[];
  /**
   * Who is inside which room right now, grouped by room id. Rooms with nobody in
   * them are simply absent, so callers merge this against the full room list.
   */
  getOccupancyByRoom: () => {
    roomId: string | null;
    room: string;
    count: number;
    people: ClockInRecord[];
  }[];
  getAllRecords: () => ClockInRecord[];
  getRecordsByDate: (date: Date) => ClockInRecord[];
  fetchRecords: () => Promise<void>;
  fetchTodayRecords: () => Promise<void>;
}

/**
 * Formats the generated `duration_minutes` for display. Postgres owns the number;
 * this only turns it into something readable, and shows an em dash while the
 * visit is still open.
 */
export function formatDurationMinutes(minutes: number | null): string {
  if (minutes === null || minutes === undefined || !Number.isFinite(minutes)) {
    return '—';
  }
  if (minutes < 0) return '—';
  const hours = Math.floor(minutes / 60);
  const mins = Math.floor(minutes % 60);
  return `${hours}h ${mins}m`;
}

/**
 * `rooms` is joined for display because the room is stored by id, and the
 * user's name is joined rather than copied so it cannot drift.
 */
const SELECT = `*,
      users:user_id (name),
      rooms:room_id (room_number, name, building),
      purposes:purpose_id (label)`;

function mapRow(record: any): ClockInRecord {
  return {
    id: record.id,
    userId: record.user_id,
    userName: record.users?.name || 'Unknown User',
    roomId: record.room_id ?? null,
    room: record.rooms?.room_number || 'Unassigned',
    building: record.rooms?.building ?? null,
    purposeId: record.purpose_id ?? null,
    purposeLabel: record.purposes?.label ?? null,
    timeIn: new Date(record.time_in),
    timeOut: record.time_out ? new Date(record.time_out) : null,
    // Both of these are GENERATED columns. They are read, never written.
    status: (record.status as 'active' | 'completed') ?? 'active',
    durationMinutes: record.duration_minutes ?? null,
  };
}

export const useRecordsStore = create<RecordsState>((set, get) => ({
  records: [],
  isLoading: false,

  addRecord: async (data) => {
    set({ isLoading: true });
    
    try {
      // `status` and `duration_minutes` are deliberately absent: Postgres
      // generates them, and an INSERT that names them is rejected outright.
      const { data: recordData, error } = await supabase
        .from('clock_in_records')
        .insert([
          {
            user_id: data.userId,
            room_id: data.roomId ?? null,
            purpose_id: data.purposeId ?? null,
            time_in: data.timeIn.toISOString(),
          },
        ])
        .select(SELECT)
        .single();

      if (error) {
        set({ isLoading: false });
        return { success: false, error: error.message };
      }

      if (recordData) {
        const newRecord = mapRow(recordData);

        set((state) => ({
          records: [newRecord, ...state.records],
          isLoading: false
        }));

        return { success: true, recordId: recordData.id };
      }

      return { success: true };
    } catch (error) {
      set({ isLoading: false });
      return { success: false, error: 'An unexpected error occurred' };
    }
  },

  clockOutRecord: async (recordId) => {
    set({ isLoading: true });
    
    try {
      const timeOut = new Date();

      // Confirm the row exists before closing it. After a page refresh this store
      // starts empty, so bailing out with "not found" would leave the row stuck
      // open forever.
      const { data: existing, error: lookupError } = await supabase
        .from('clock_in_records')
        .select('id, time_out')
        .eq('id', recordId)
        .maybeSingle();

      if (lookupError) {
        set({ isLoading: false });
        return { success: false, error: lookupError.message };
      }

      if (!existing) {
        set({ isLoading: false });
        return { success: false, error: 'This check-in record no longer exists.' };
      }

      if (existing.time_out) {
        // Already closed. Reported as success so a retry is harmless rather than
        // an error the visitor has to interpret.
        set({ isLoading: false });
        return { success: true };
      }

      // Only time_out is written. Postgres recomputes status and
      // duration_minutes from it.
      const { data: updated, error } = await supabase
        .from('clock_in_records')
        .update({ time_out: timeOut.toISOString() })
        .eq('id', recordId)
        .select(SELECT)
        .single();

      if (error) {
        set({ isLoading: false });
        return { success: false, error: error.message };
      }

      // Read back rather than patching in memory, so the generated columns on
      // this row are the values Postgres actually stored.
      const closed = mapRow(updated);

      set((state) => ({
        records: state.records.map((r) => (r.id === recordId ? closed : r)),
        isLoading: false,
      }));

      return { success: true };
    } catch (error) {
      set({ isLoading: false });
      return { success: false, error: 'An unexpected error occurred' };
    }
  },

  getActiveCount: () => {
    return get().records.filter((r) => r.status === 'active').length;
  },

  getActiveRecords: () => {
    return get().records.filter((r) => r.status === 'active');
  },

  getOccupancyByRoom: () => {
    const byRoom = new Map<string, ClockInRecord[]>();

    for (const record of get().records) {
      if (record.status !== 'active') continue;

      // A null room_id is legitimate - someone can clock in before being assigned
      // one - so it buckets under a sentinel rather than being dropped.
      const key = record.roomId ?? 'unassigned';
      const people = byRoom.get(key);
      if (people) {
        people.push(record);
      } else {
        byRoom.set(key, [record]);
      }
    }

    // Busiest room first so the rooms that need attention lead the list.
    return Array.from(byRoom.entries())
      .map(([key, people]) => ({
        roomId: key === 'unassigned' ? null : key,
        room: people[0]?.room || 'Unassigned',
        count: people.length,
        people,
      }))
      .sort((a, b) => b.count - a.count || a.room.localeCompare(b.room));
  },

  getTodayCount: () => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return get().records.filter((r) => {
      const recordDate = new Date(r.timeIn);
      recordDate.setHours(0, 0, 0, 0);
      return recordDate.getTime() === today.getTime();
    }).length;
  },

  getCompletedTodayCount: () => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return get().records.filter((r) => {
      const recordDate = new Date(r.timeIn);
      recordDate.setHours(0, 0, 0, 0);
      return (
        recordDate.getTime() === today.getTime() &&
        r.status === 'completed'
      );
    }).length;
  },

  getAllRecords: () => {
    return get().records;
  },

  getRecordsByDate: (date) => {
    const targetDate = new Date(date);
    targetDate.setHours(0, 0, 0, 0);
    
    return get().records.filter((r) => {
      const recordDate = new Date(r.timeIn);
      recordDate.setHours(0, 0, 0, 0);
      return recordDate.getTime() === targetDate.getTime();
    });
  },

  fetchRecords: async () => {
    set({ isLoading: true });

    try {
      const { data, error } = await supabase
        .from('clock_in_records')
        .select(SELECT)
        .order('time_in', { ascending: false });

      if (error) {
        console.error('Error fetching records:', error);
        set({ isLoading: false });
        return;
      }

      if (data) {
        set({ records: data.map(mapRow), isLoading: false });
      }
    } catch (error) {
      console.error('Error fetching records:', error);
      set({ isLoading: false });
    }
  },

  fetchTodayRecords: async () => {
    set({ isLoading: true });

    try {
      const today = new Date();
      today.setHours(0, 0, 0, 0);
      const todayISO = today.toISOString();

      const { data, error } = await supabase
        .from('clock_in_records')
        .select(SELECT)
        .gte('time_in', todayISO)
        .order('time_in', { ascending: false });

      if (error) {
        console.error('Error fetching today records:', error);
        set({ isLoading: false });
        return;
      }

      if (data) {
        set({ records: data.map(mapRow), isLoading: false });
      }
    } catch (error) {
      console.error('Error fetching today records:', error);
      set({ isLoading: false });
    }
  },
}));
