import { create } from 'zustand';
import { supabase } from '@/lib/supabase';

/**
 * Room presence tracking.
 *
 * This is deliberately NOT attendance. Attendance lives in `clock_in_records`
 * and is only ever written by scanning the ground floor station code (see
 * `clockInStore` / `recordsStore`). Presence here answers a narrower question:
 * of the people currently checked in, which room is each one sitting in right
 * now?
 *
 * Rows are append-only. Scanning a room door opens a row with `entered_at` and
 * no `exited_at`; scanning a different room (or the same one again) closes the
 * open row first. Keeping the history means "who was in Room 304 at 3pm" is
 * answerable, not just "who is in it now".
 */

export interface RoomPresence {
  id: string;
  userId: string;
  userName?: string;
  /** FK to rooms.id. The room is referenced by id, never copied as text. */
  roomId: string;
  /** Room number, joined from `rooms` for display. Not a column on this table. */
  room: string;
  roomLabel: string;
  /** The attendance visit this room entry happened under. */
  clockInId: string | null;
  enteredAt: Date;
  exitedAt: Date | null;
  /** Generated by Postgres. Null while the visit is still open. */
  durationMinutes: number | null;
}

interface RoomPresenceState {
  presence: RoomPresence[];

  /**
   * Records that the user is in `roomId` now, closing any room they were in
   * before (R4). Returns the new open row's id on success.
   */
  enterRoom: (params: {
    userId: string;
    roomId: string;
    /** Links the visit to the open attendance row so history stays per-visit. */
    clockInId?: string | null;
  }) => Promise<{
    success: boolean;
    error?: string;
    presenceId?: string;
    /**
     * True when the scan named the room they are already recorded in. Nothing
     * was written; the caller shows a notice instead of a new visit.
     */
    alreadyInRoom?: boolean;
  }>;

  /** Closes the user's currently open row, if any. */
  leaveRoom: (userId: string) => Promise<{ success: boolean; error?: string }>;

  /** The room the user is in right now, or null if nowhere tracked. */
  getCurrentRoom: (userId: string) => RoomPresence | null;

  /** Everyone with an open row, grouped by room id. Rooms with nobody are absent. */
  getOccupancyByRoom: () => {
    roomId: string;
    room: string;
    roomLabel: string;
    people: RoomPresence[];
  }[];

  getPresenceCount: () => number;
  fetchTodayPresence: () => Promise<void>;
  /** Full history, not just today. Used by the admin room-visits page. */
  fetchAllPresence: () => Promise<void>;
  /** Visits to one room, newest first. */
  getVisitsByRoom: (roomId: string) => RoomPresence[];
  /** Rooms that have at least one visit, with their totals. */
  getRoomSummaries: () => RoomSummary[];
}

/**
 * `rooms` is joined for the display name because room_visits has no room_label.
 * The user's name is joined rather than stored, so it can never drift.
 */
const SELECT = `*,
    users:user_id (name),
    rooms:room_id (room_number, name)`;

function mapRow(row: any): RoomPresence {
  return {
    id: row.id,
    userId: row.user_id,
    userName: row.users?.name || 'Unknown User',
    roomId: row.room_id,
    room: row.rooms?.room_number || '',
    roomLabel: row.rooms?.name || row.rooms?.room_number || 'Unknown Room',
    clockInId: row.clock_in_id ?? null,
    enteredAt: new Date(row.entered_at),
    exitedAt: row.exited_at ? new Date(row.exited_at) : null,
    durationMinutes: row.duration_minutes ?? null,
  };
}

/** How long someone spent in a room, from their own two timestamps. */
export function visitDuration(enteredAt: Date, exitedAt: Date | null): string {
  if (!exitedAt) return '—';
  // A negative span means the clock moved (DST, or a device with a skewed
  // clock). Showing a negative "duration" would be worse than showing nothing.
  return formatDuration(exitedAt.getTime() - enteredAt.getTime());
}

/** Per-room totals for the admin page. */
export interface RoomSummary {
  roomId: string;
  room: string;
  roomLabel: string;
  totalVisits: number;
  insideNow: number;
  uniqueVisitors: number;
  /** Mean length of completed visits, or null when nothing has left yet. */
  averageDuration: string | null;
}

/** Formats a span in ms. Negative spans return an em dash rather than "-5m". */
function formatDuration(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return '—';
  const hours = Math.floor(ms / (1000 * 60 * 60));
  const minutes = Math.floor((ms % (1000 * 60 * 60)) / (1000 * 60));
  return hours > 0 ? `${hours}h ${minutes}m` : `${minutes}m`;
}

export const useRoomPresenceStore = create<RoomPresenceState>((set, get) => ({
  presence: [],

  enterRoom: async ({ userId, roomId, clockInId }) => {
    try {
      // Close whatever room they were in first, so they can never be counted
      // in two rooms at once. This is also what stops the
      // `room_visits_one_open_per_user` partial unique index from tripping on
      // the insert below (R4). Deliberately tolerant of failure: if this update
      // fails we still record the new room rather than losing the scan, but the
      // stale row stays open and shows up in occupancy until it's fixed.
      const { data: openRows, error: openError } = await supabase
        .from('room_visits')
        .select('id, room_id')
        .eq('user_id', userId)
        .is('exited_at', null);

      if (!openError && openRows && openRows.length > 0) {
        // Already recorded in this exact room. Scanning the same door again is a
        // no-op rather than a new visit: closing and reopening would inflate the
        // visit count and reset the "inside since" time for no reason. The
        // caller shows a "you're already here" notice instead.
        const sameRoom = openRows.find((r) => r.room_id === roomId);
        if (sameRoom) {
          return {
            success: false,
            alreadyInRoom: true,
            error: 'You are already inside this room.',
          };
        }

        await supabase
          .from('room_visits')
          .update({ exited_at: new Date().toISOString() })
          .in(
            'id',
            openRows.map((r) => r.id)
          );
      }

      const { data, error } = await supabase
        .from('room_visits')
        .insert([
          {
            user_id: userId,
            room_id: roomId,
            // Without this the room trail blurs across days for anyone who
            // checks in more than once.
            clock_in_id: clockInId ?? null,
            entered_at: new Date().toISOString(),
          },
        ])
        .select(SELECT)
        .single();

      if (error) {
        return { success: false, error: error.message };
      }

      const row = mapRow(data);
      set((state) => ({ presence: [row, ...state.presence] }));

      return { success: true, presenceId: data.id };
    } catch {
      return { success: false, error: 'An unexpected error occurred' };
    }
  },

  leaveRoom: async (userId) => {
    try {
      const { error } = await supabase
        .from('room_visits')
        .update({ exited_at: new Date().toISOString() })
        .eq('user_id', userId)
        .is('exited_at', null);

      if (error) {
        return { success: false, error: error.message };
      }

      const now = new Date().toISOString();
      set((state) => ({
        presence: state.presence.map((p) =>
          p.userId === userId && !p.exitedAt ? { ...p, exitedAt: new Date(now) } : p
        ),
      }));

      return { success: true };
    } catch {
      return { success: false, error: 'An unexpected error occurred' };
    }
  },

  getCurrentRoom: (userId) =>
    get().presence.find((p) => p.userId === userId && !p.exitedAt) ?? null,

  getOccupancyByRoom: () => {
    const byRoom = new Map<string, RoomPresence[]>();

    for (const entry of get().presence) {
      if (entry.exitedAt) continue;
      const list = byRoom.get(entry.roomId) ?? [];
      list.push(entry);
      byRoom.set(entry.roomId, list);
    }

    return Array.from(byRoom.entries()).map(([roomId, people]) => ({
      roomId,
      room: people[0]?.room || '',
      roomLabel: people[0]?.roomLabel || 'Unknown Room',
      people,
    }));
  },

  getPresenceCount: () => get().presence.filter((p) => !p.exitedAt).length,

  getVisitsByRoom: (roomId) =>
    get()
      .presence.filter((p) => p.roomId === roomId)
      .sort((a, b) => b.enteredAt.getTime() - a.enteredAt.getTime()),

  getRoomSummaries: () => {
    const byRoom = new Map<string, RoomPresence[]>();

    for (const entry of get().presence) {
      const list = byRoom.get(entry.roomId) ?? [];
      list.push(entry);
      byRoom.set(entry.roomId, list);
    }

    return Array.from(byRoom.entries()).map(([roomId, visits]) => {
      // Only visits that have both timestamps AND a sane ordering can contribute
      // to the average. Summing the bad ones would drag the mean down (or make
      // it negative) for the whole room.
      const spans = visits
        .filter((v) => v.exitedAt)
        .map((v) => v.exitedAt!.getTime() - v.enteredAt.getTime())
        .filter((ms) => ms >= 0);

      return {
        roomId,
        room: visits[0]?.room || '',
        roomLabel: visits[0]?.roomLabel || 'Unknown Room',
        totalVisits: visits.length,
        insideNow: visits.filter((v) => !v.exitedAt).length,
        uniqueVisitors: new Set(visits.map((v) => v.userId)).size,
        averageDuration:
          spans.length > 0
            ? formatDuration(spans.reduce((a, b) => a + b, 0) / spans.length)
            : null,
      };
    });
  },

  fetchAllPresence: async () => {
    try {
      const { data, error } = await supabase
        .from('room_visits')
        .select(SELECT)
        .order('entered_at', { ascending: false });

      if (error) {
        console.error('Error fetching room visit history:', error);
        return;
      }

      if (data) {
        set({ presence: data.map(mapRow) });
      }
    } catch (error) {
      console.error('Error fetching room visit history:', error);
    }
  },

  fetchTodayPresence: async () => {
    try {
      const today = new Date();
      today.setHours(0, 0, 0, 0);

      const { data, error } = await supabase
        .from('room_visits')
        .select(SELECT)
        .gte('entered_at', today.toISOString())
        .order('entered_at', { ascending: false });

      if (error) {
        console.error('Error fetching room presence:', error);
        return;
      }

      if (data) {
        set({ presence: data.map(mapRow) });
      }
    } catch (error) {
      console.error('Error fetching room presence:', error);
    }
  },
}));
