import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

// Typed schemas for this project are intentionally absent.
//
// An earlier version carried a hand-written `Database` interface here describing
// the pre-migration tables. It was never imported and never passed to
// `createClient`, so it enforced nothing, and it had drifted badly: it declared
// a `schedules` table that exists in no migration, plus writable `status` and
// `duration` columns that are now GENERATED by Postgres (naming them in an
// INSERT fails outright).
//
// Leaving it was worse than having nothing: it contradicted the invariants in
// IMPLEMENTATION_PROMPT.md §5 and would have led the next reader to write code
// against a schema that does not exist.
//
// If type-safe queries are wanted later, generate them from the live schema
// rather than hand-maintaining them, so they cannot drift:
//
//   npx supabase gen types typescript --project-id <ref> --schema public
//
// That writes a file describing what the database actually is. Hand-editing it
// recreates the exact problem this deletion removes.
