// Roster source data for the orientation cohort.
// Columns: [programme, last, first, middle, middleInitial, extension, email]
// `null` means the source roster had no value there.

const BARISTA = 'Barista NC II';
const EVENTS = 'Event Management Services NC II';
const HOUSEKEEPING = 'Housekeeping NC II';
const HILOT = 'Hilot (Wellness) Services NC II';
const MASSAGE = 'Massage NC II';

module.exports = [
  // ---------------------------------------------------------------- Barista
  [BARISTA, 'Aranda', 'Gemmalyn', 'Ocbina', 'O.', null, 'gemmaaranda05@gmail.com'],
  [BARISTA, 'Marquez', 'Prince Jhazkhie', 'Asis', 'A.', null, 'marquezprincejhazkie@gmail.com'],
  [BARISTA, 'Antalan', 'Mary Grace', 'Miclat', 'M.', null, 'maryysmiclat@gmail.com'],
  [BARISTA, 'Corsanes', 'Chryss Jericho', 'Nalla', 'N.', null, 'chryssjerichocorsanes12@gmail.com'],
  [BARISTA, 'Gardoce', 'Jeffrey', 'Antipuesto', 'A.', null, 'jefgardoce12@gmail.com'],
  [BARISTA, 'Ilagan', 'Jhay', 'N/A', null, null, 'jhaylynilagan532@gmail.com'],
  [BARISTA, 'Lucero', 'Ana Mae', 'Samentar', 'S.', null, null],
  [BARISTA, 'Sta. Romana', 'Richard', 'Bello', 'B.', null, 'staromanarichard@gmail.com'],
  [BARISTA, 'Onelongo', 'Veronica', 'Manapat', 'M.', null, 'vonelongo@gmail.com'],
  [BARISTA, 'Canes', 'Daniel', 'Manging', 'M.', null, null],
  [BARISTA, 'Puntual', 'Judah', 'Aggabao', 'A.', null, 'judahpuntual7@gmail.com'],
  [BARISTA, 'Santos', 'Maui', 'Natalicio', 'M.', null, 'mauikengkay@gmail.com'],
  [BARISTA, 'Zuela', 'Jasmine Chlouie', 'Sapu-an', 'S.', null, 'zuelajasmine@gmail.com'],
  [BARISTA, 'Padilla', 'Gabrielle', 'Tagle', 'T.', null, null],
  [BARISTA, 'Casinto', 'Lance', 'Davocol', 'D.', null, 'lancecasinto1407@gmail.com'],
  [BARISTA, 'Olog', 'Marca Angela', 'Liberato', 'L.', null, 'ologmarca@gmail.com'],
  [BARISTA, 'Mapalad', 'Veronica', 'Agsangre', 'A.', null, 'mapalad2005@gmail.com'],
  [BARISTA, 'Borja', 'Shaira Marie', 'Bernardino', 'B.', null, 'marieborja@yahoo.com'],
  [BARISTA, 'Bulalacao', 'Annie', 'Pamintuan', 'A.', null, 'anniebulalacao048@gmail.com'],
  [BARISTA, 'Maestre', 'John Carlo', 'Logenic', 'L.', null, 'johncarlomaestre0807@gmail.com'],
  [BARISTA, 'Quibin', 'Angelica Marie', 'N/A', null, null, 'angelicaquibin30@gmail.com'],
  [BARISTA, 'Firmalino', 'Ma. Isabel', 'Parulan', 'P.', null, 'mipfirmadino@gmail.com'],
  [BARISTA, 'Quijada', 'Rodel', 'Camelotes', 'C.', null, 'rodelcamelotesquijada@gmail.com'],
  [BARISTA, 'Palo', 'Joancen', 'Rodriguez', 'R.', null, 'joancenfame@gmail.com'],
  [BARISTA, 'Escalera', 'Buenafe', 'Visca', 'V.', null, 'buenafe71escalera@yahoo.com'],
  [BARISTA, 'Tuazon', 'Francis', 'Pigar', 'P.', null, 'francistuazon234@gmail.com'],
  [BARISTA, 'Evans', 'May', 'Valdez', 'V.', null, 'mayvaldezqc@yahoo.com'],
  [BARISTA, 'Casiano', 'Daniella', 'N/A', null, null, null],
  [BARISTA, 'Carpio', 'John Lloyd', 'Yadawon', 'Y.', null, 'johnlloydcarpio0246@gmail.com'],
  [BARISTA, 'Artesano', 'Shanlege Nicole', 'Tortusia', 'T.', null, 'artesanoshanlegh@gmail.com'],
  [BARISTA, 'Fernandez', 'Zyraclaire', 'Carillo', 'C.', null, 'zyrafernandez73@gmail.com'],
  [BARISTA, 'Patso', 'Julia Mae', 'Tordecilla', 'T.', null, 'juliapateo0@gmail.com'],
  [BARISTA, 'Mabato', 'Ruby Ann', 'Maquimot', 'M.', null, 'bmaquimot@gmail.com'],
  [BARISTA, 'Carillo', 'Railey', 'Mandapat', 'M.', null, 'raileycarillois@gmail.com'],
  [BARISTA, 'Samolden', 'Esrafil', 'Madlawi', 'E.', null, 'esrafilmadlawi2026@gmail.com'],
  [BARISTA, 'Ramos', 'Chevie Sheen', 'Zamora', 'Z.', null, 'ramoschevie@gmail.com'],
  [BARISTA, 'Cruz', 'Romel Jhon Nickelson', 'Cruz', 'C.', null, 'nickelsonos@gmail.com'],
  [BARISTA, 'Subalisid', 'Erwin', 'Deinla', 'D.', null, 'erwinmahiligsumisio069@gmail.com'],
  [BARISTA, 'Corpuz', 'Joshua Miguel', 'N/A', null, null, null],
  [BARISTA, 'Cortez', 'Diana', 'Camento', 'C.', null, null],
  [BARISTA, 'Marmita', 'Reinmah Iya', 'Tabor', 'T.', null, 'reinnahiyatabormarmita@gmail.com'],
  [BARISTA, 'Perez', 'Lester', 'Dapi', 'D.', null, 'perezlester029@gmail.com'],
  [BARISTA, 'Molina', 'Donnadel', 'Benavidez', 'B.', null, 'mrichynicho0301@gmail.com'],
  [BARISTA, 'Plotria', 'Sheila', 'Ajos', 'A.', null, 'splotria@gmail.com'],
  [BARISTA, 'Ramirez', 'Alyza', 'Ann', 'A.', null, null],
  [BARISTA, 'Canete', 'Cyrill', 'Divinaflor', 'D.', null, 'cyrill.divinaflor.canete@gmail.com'],
  [BARISTA, 'Reyes', 'Kimberly Shine', 'Bago', 'B.', null, 'rkim09391@gmail.com'],
  [BARISTA, 'Rojas', 'Stephanie', 'Omalza', 'O.', null, null],
  [BARISTA, 'Manozo', 'John', 'Patrick', 'S.', null, 'johnpatrickmanozo@gmail.com'],
  [BARISTA, 'Simon', 'Jocelle', 'Diaz', 'D.', null, 'simonjocelle.diaz@gmail.com'],
  [BARISTA, 'Hernandez', 'Ciauel', 'Lozada', 'L.', null, 'ciauelhernandez0@gmail.com'],
  [BARISTA, 'Geronimo', 'Chrizelle Kelly', 'N/A', null, null, 'chrizellekellygeronimo@gmail.com'],
  [BARISTA, 'Derueda', 'Quincie Jell', 'Davocol', 'D.', null, 'quinciejell02@gmail.com'],
  [BARISTA, 'Mercado', 'Carmina', 'Gerona', 'G.', null, 'carminagerano@gmail.com'],
  [BARISTA, 'Oro', 'Gaveriell', 'N/A', null, null, null],
  [BARISTA, 'Hernandez', 'Kyra Isabel', 'Carolino', 'C.', null, 'kyraisabel.h@gmail.com'],
  [BARISTA, 'Yebra', 'Angel', 'Ann', 'O.', null, 'yebra.angelann.oroi@gmail.com'],
  [BARISTA, 'Jamito', 'Kylle', 'Justine', 'J.', null, 'kyllejustine.jamito08@gmail.com'],
  // ------------------------------------------------- Event Management
  [EVENTS, 'Ramos', 'Marites', 'Antonino', 'A.', null, 'maritesaramos70@gmail.com'],
  [EVENTS, 'Uy', 'Athena Karyle', 'Daliposon', 'D.', null, 'athenakaryvevy@gmail.com'],
  [EVENTS, 'Bautista', 'Maria Michelle', 'Esteban', 'E.', null, 'bautistamariemichelle0923@gmail.com'],
  [EVENTS, 'Barcelona', 'Lourdes', 'Bartolome', 'B.', null, null],
  [EVENTS, 'Jadulco', 'Genrina', 'Peralta', 'P.', null, 'genrinajadulco@gmail.com'],
  [EVENTS, 'Bismonte', 'Jemuel', 'Banzale', 'B.', null, 'jemuelbanzalebismonte@gmail.com'],
  [EVENTS, 'Barbin', 'Aldrin', 'Bayoca', 'B.', null, 'aldrinbarbib467@gmail.com'],
  [EVENTS, 'Nadal', 'Ma. Shangrila', 'Santos', 'S.', null, 'shanna.nadal.v2@gmail.com'],
  [EVENTS, 'Bantug', 'Shine', 'Mary', 'C.', null, 'bantugshinemary@gmail.com'],
  [EVENTS, 'Amargo', 'Jade', 'Russel', 'Y.', null, 'jaderussel.jra@gmail.com'],

  // ---------------------------------------------------------- Housekeeping
  [HOUSEKEEPING, 'Prendol', 'Maria Michelle', 'Melchor', 'M.', null, 'atchiethienekoh@gmail.com'],
  [HOUSEKEEPING, 'Lanas', 'Maria Flor', 'Deguit', 'D.', null, 'mariaflordeguitlanas02@gmail.com'],
  [HOUSEKEEPING, 'Ocampo', 'Rodora', 'Balhag', 'B.', null, 'rodora0512@gmail.com'],
  [HOUSEKEEPING, 'Ocampo', 'Adryan', 'Sales', 'S.', null, 'adryan1026@gmail.com'],
  [HOUSEKEEPING, 'Daban', 'Rosanna', 'Valdez', 'V.', null, 'annasordaban@gmail.com'],
  [HOUSEKEEPING, 'Tuazon', 'Anghellina', 'Pigar', 'P.', null, null],
  [HOUSEKEEPING, 'Latorre', 'Judy Ann', 'Delmonte', 'D.', null, 'jalatorre2022@gmail.com'],
  [HOUSEKEEPING, 'Pepe', 'Jannet', 'Maestre', 'M.', null, null],
  [HOUSEKEEPING, 'Abuda', 'Abbigayle', 'Olivar', 'O.', null, null],
  [HOUSEKEEPING, 'Galvez', 'Ginalyn', 'Canes', 'G.', null, 'galvezginalyn8@gmail.com'],
  [HOUSEKEEPING, 'Tuazon', 'Marialyn', 'Pigar', 'M.', null, null],
  [HOUSEKEEPING, 'Rublica', 'Kelvin', 'Delima', 'K.', null, null],
  [HOUSEKEEPING, 'Mariot', 'Maria Carmen', 'Torres', 'T.', null, null],
  [HOUSEKEEPING, 'Dela Cruz', 'Amelia', 'Rocacorba', 'R.', null, null],
  [HOUSEKEEPING, 'Rowaya', 'Julan', 'N/A', null, null, 'rowayajulan@gmail.com'],
  [HOUSEKEEPING, 'Valenciado', 'Joyce Mar', 'Albesa', 'A.', null, 'valenciadojoycemar@gmail.com'],
  [HOUSEKEEPING, 'Lalic', 'Joses Kyle', 'N/A', null, null, 'joky.lalicshc@phinmaed.com'],
  [HOUSEKEEPING, 'Dacayo', 'Nicko', 'Saturnino', 'S.', null, 'nsd.prosperity@gmail.com'],
  [HOUSEKEEPING, 'Aranda', 'Edmond', 'Ocbina', 'O.', null, 'edmondaranda97@gmail.com'],
  [HOUSEKEEPING, 'Doria', 'Lourdes', 'Lontoc', 'L.', null, 'lourdesairod252@gmail.com'],
  [HOUSEKEEPING, 'Macapagal', 'Joel', 'Dela Cruz', 'D.', null, 'macapagalj@gmail.com'],
  [HOUSEKEEPING, 'Gutierrez', 'Bea Marie', 'Traboc', 'B.', null, 'beamariegutierrez2@gmail.com'],
  [HOUSEKEEPING, 'Estrella', 'Lyra', 'Gonzales', 'G.', null, 'lyragonzales1824@gmail.com'],
  [HOUSEKEEPING, 'Cano', 'Jomer Boy', 'Enero', 'J.', null, 'jomercano54@gmail.com'],
  [HOUSEKEEPING, 'Cano', 'James Hooper', 'Enero', 'J.', null, 'jameshoopercano03@gmail.com'],
  [HOUSEKEEPING, 'Palo', 'Brian Griffin', 'Rodriguez', 'B.', null, 'nairbolap.0824@gmail.com'],
  [HOUSEKEEPING, 'Longasa', 'Rhica Shaira', 'Jimenez', 'R.', null, 'longasarhicashaira@gmail.com'],
  [HOUSEKEEPING, 'Lim', 'Cielo', 'De La Cruz', 'D.', null, 'cielolim1423271994@gmail.com'],
  [HOUSEKEEPING, 'Marasigan', 'Riana Jean', 'Dumantay', 'R.', null, 'rianajean08@gmail.com'],
  [HOUSEKEEPING, 'Teniente', 'Vea Rafhaela', 'Betita', 'V.', null, 'veateniente091528@gmail.com'],
  [HOUSEKEEPING, 'Recoco', 'Reina Mae', 'Plaza', 'R.', null, 'reinarecoco@gmail.com'],
  [HOUSEKEEPING, 'Daisog', 'Mary Joy', 'Masilang', 'M.', null, 'daisogmaryjoy123@gmail.com'],
  [HOUSEKEEPING, 'Labuntog', 'Ma. Cleotelde', 'Navalle', 'N.', null, 'mariacleotilde18@yahoo.com'],
  [HOUSEKEEPING, 'Lotero', 'Krishea', 'Mae', 'M.', null, 'krishamaedanaslotero@gmail.com'],
  [HOUSEKEEPING, 'Labuntog', 'Vanessa', 'Mae', 'M.', null, null],
  [HOUSEKEEPING, 'Magabulo', 'Nicole', 'N/A', null, null, 'nicolemagabulo17@gmail.com'],
  [HOUSEKEEPING, 'Requiroso', 'Loida', 'N/A', 'B.', null, null],
  [HOUSEKEEPING, 'Aquino', 'Blessie', 'N/A', 'E.', null, 'blessie.aquino0730@gmail.com'],
  [HOUSEKEEPING, 'Navarro', 'Jonalie', 'N/A', 'P.', null, 'jonaliemaenavarro@gmail.com'],
  [HOUSEKEEPING, 'Infestan', 'Patrick', 'N/A', null, null, 'infestanpatrick147@gmail.com'],
  [HOUSEKEEPING, 'Sinner', 'Dianne', 'Cacho', 'D.', null, 'dianneainner2@gmail.com'],
  [HOUSEKEEPING, 'Narte', 'Annalyn', 'Bernardino', 'B.', null, 'annabernardino@gmail.com'],
  [HOUSEKEEPING, 'Tizon', 'Ivy', 'N/A', 'N.', null, 'ibyoungs17@gmail.com'],
  [HOUSEKEEPING, 'Custodio', 'Jhelene', 'Clyde', 'C.', null, 'jheleneclyde.custudio@tup.edu.ph'],
  [HOUSEKEEPING, 'Sulla', 'Rendelyn', 'N/A', 'B.', null, 'rendelynsulla@gmail.com'],
  [HOUSEKEEPING, 'Galang', 'Elgine', 'N/A', null, null, 'galangelgine@gmail.com'],
  [HOUSEKEEPING, 'Janito', 'Lyndie', 'N/A', 'A.', null, 'lyndiejanitoIIII@gmail.com'],
  [HOUSEKEEPING, 'Carmona', 'Mark', 'N/A', 'R.', null, 'kramanomrac42@gmail.com'],
  [HOUSEKEEPING, 'Binamira', 'Ronald', 'N/A', null, null, 'onatbinamira000@gmail.com'],
  [HOUSEKEEPING, 'Garcia', 'Cecillia', 'N/A', 'P.', null, 'cg4512933@gmail.com'],
  [HOUSEKEEPING, 'Dollaga', 'Henrietta', 'N/A', 'M.', null, 'henriemdollaga@gmail.com'],
  [HOUSEKEEPING, 'Dollaga', 'Ailene', 'N/A', 'L.', null, 'ailenedollaga0922@gmail.com'],

  // ------------------------------------------ Hilot (Wellness) Services
  [HILOT, 'Yu', 'Jane', 'Godezano', 'G.', null, 'janeyu12@gmail.com'],
  [HILOT, 'Pamana', 'Jose Romel', 'Dellova', 'D.', null, null],
  [HILOT, 'Dela Cruz', 'Marjorie', 'Acedera', 'A.', null, null],
  [HILOT, 'Bajada', 'Honey Beth', 'Jabineao', 'J.', null, null],
  [HILOT, 'Guerrero', 'Ma. Alexa', 'Asuncion', 'A.', null, 'asuncionalexa420@gmail.com'],
  [HILOT, 'Rojas', 'Sharon', 'N/A', 'B.', null, 'baconawasharonrojas@gmail.com'],
  [HILOT, 'Dadis', 'Erjielyn', 'N/A', 'C.', null, 'erjiedadis6@gmail.com'],
  [HILOT, 'Lorenzana', 'Alma', 'N/A', 'C.', null, 'almalorenzana911@gmail.com'],
  [HILOT, 'Oblipias', 'Rissa', 'N/A', 'A.', null, 'rissaoblipias88@gmail.com'],
  [HILOT, 'Fernandez', 'Erwin', 'N/A', 'D.', null, 'erwindgfernandez@gmail.com'],

  // -------------------------------------------------------------- Massage
  [MASSAGE, 'Pamintuan', 'Mario', 'Pingul', 'P.', null, null],
];